### ISSUE TITLE
Support Multiple API Endpoints

### ISSUE THREAD

**Issue by salvianreynaldi** [open-rpc/mock-server#223]
**Is your feature request related to a problem? Please describe.**
The current implementation "mounts" one open-rpc document to any server paths (i.e. "http://localhost:3333/", "http://localhost:3333/anyrandomstring" all routes to the doc). However, an RPC server could have multiple servlets, where different paths routes to different servlets.

**Describe the solution you'd like**
1. The `-d` CLI option points to a directory which may contains multiple openRPC docs
2. Filesystem-path based servlets relative to the pointed directory, e.g.
```
./userServlet/user-openrpc.json --> http://localhost:3333/userServlet
./paymentServlet/payment-openrpc.json --> http://localhost:3333/paymentServlet
```

**Describe alternatives you've considered**
Alt 1. Run a dedicated mock server for each of the servlets, each with different port. This seems inefficient
Alt 2. Describe the servlet path in openrpc [Server Object's url](https://spec.open-rpc.org/#server-object)

**Comment by BelfordZ** [comment]
hey @salvianreynaldi thanks for the issue.

Just so I understand more clearly, are you referring to the `service` mode of service runner? It's not currently documented =(

But you can run it with 
`open-rpc-mock-server -m service`  - this allows you to add apis on the fly, as you suggested.

Its quite a new feature.. at the moment it works for 15m and then removes it. You can try the deployed version of it at https://mock.open-rpc.org

**Comment by salvianreynaldi** [comment]
Hi @BelfordZ
thanks! service mode might be what I'm looking.
If I understand it correctly, I should just call the `mock` method with the openrpc json as the parameter, and a path will be returned? Can I specify the path as a parameter as well?

**Comment by BelfordZ** [comment]
@salvianreynaldi pretty much.

I should just call the mock method with the openrpc json as the parameter -> yep
and a path will be returned? -> yep
Can I specify the path as a parameter as well? -> yep, set your OpenRPCDocument.info.title to something unique.

Im actually fixing it right now as I've notice its not working exactly as it should be ATM.
